### ISSUE TITLE
How to increase thread_queue_size?

### ISSUE THREAD

**Issue by aapopei** [AshenHermit/kept_generator#1]
I've got a lot of interruptions, and the in cmd I've got the following suggestion:

Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
Failed to update header with correct duration.
Failed to update header with correct filesize.

How can I increase/fix this?

https://ibb.co/Lt2zG3w

**Comment by AshenHermit** [comment]
All these warnings and errors come from [ffmpeg](https://ffmpeg.org/).  
`thread_queue_size` can be set using the argument for the ffmpeg command, which is in method `broadcast_part` in [shuffling_broadcaster.py](./shuffling_broadcaster.py)  
like so: `-thread_queue_size 1024`, 1024 is the value.  
Just in case, I added the env variable `BROADCAST_OPTIONS` for similar arguments. [commit](https://github.com/AshenHermit/kept_generator/commit/dd9422f0e2dd0c932b7b10820893fb32734fd59e).
  
Warnings `Failed to update header with correct duration` and `filesize` seem ok, I have them too.  
And i also have errors `av_interleaved_write_frame` and `Error writing trailer of pipe:: Invalid argument`.
But your `Error closing file pipe:: Invalid Argument` scares. Does the program broadcast any data?

**Comment by aapopei** [comment]
Iuhuu, now it's working better. Thanks for the commit and suggestions.
